version: "3"
services:
  orders:
    build: ../../order-service
    ports:
    - "8081:8080"
    networks:
    - kafka-network
  inventory:
    build: ../../inventory-service-spring
    ports:
    - "8082:8080"
    networks:
    - kafka-network

networks:
  kafka-network:
    external:
      name: kafka_kafka-network
